### ISSUE TITLE
Add default profile.

### ISSUE THREAD

**Issue by tscalf** [Sjeanpierre/osx_vpn_manager#10]
I have grown weary of having to use `--profile` with each VPN connection.

Use case: 
I have 3 profiles:
```
default
prod
staging
```

80% of my PVN connections use `--profile default`.  I would like to have that be my default profile.

**Comment by Sjeanpierre** [comment]
Hi Thad,

it looks like I [fixed this issue](https://github.com/Sjeanpierre/osx_vpn_manager/commit/43a5b3ab9e1b3f05dfee628d8e7006a83917f3e5#diff-7ddfb3e035b42cd70649cc33393fe32cR22) way before you even reported it and forgot that I had built this feature into the app.
<img width="950" alt="image" src="https://cloud.githubusercontent.com/assets/673382/24582462/6aeaa8f4-16fe-11e7-93c8-d3f1eb4633a5.png">


I have however found a reason why it may not have worked for you. If you are bypassing the sudo requirement by allowing vpn command in your sudoers file, there is another update that you need to make to ensure the environment variable is preserved.
<img width="507" alt="image" src="https://cloud.githubusercontent.com/assets/673382/24582486/ddfed716-16fe-11e7-8847-3987b3831c8f.png">

If you are using a regular sudo call with each invocation of the vpn command then you will need to do it with a `-E` to preserve environment variable when switching context 

@tscalf @angelamancini
