### ISSUE TITLE
Handling multiple AWS accounts at same time

### ISSUE THREAD

**Issue by Sjeanpierre** [Sjeanpierre/osx_vpn_manager#4]

**Comment by angelamancini** [comment]
It would be nice to have an option in the vpn profile to link to which set of aws creds in the `~/.aws/credentials` file. 

So that you have `sudo vpn profile add prod`
you can tell it to use a specific profile

```
[prod]
aws_access_key_id = ACCESS_KEY
aws_secret_access_key = SECRET_KEY
```

**Comment by tscalf** [comment]
Yeah, that would be nice. :D

**Comment by Sjeanpierre** [comment]
https://github.com/andersjanmyr/route53copy/blob/ee9e79cb1de064a0e44ff95e632dfaaf40649cea/main.go#L16-L23

**Comment by angelamancini** [comment]
That looks like it could do what you need

**Comment by Sjeanpierre** [comment]
With PR #6 AWS profiles are configurable when performing host refresh, documentation will be added to readme to reflect this
